import gsap from "gsap";
import { useState, useRef } from "react";
import AnimatedTitle from "./AnimatedTitle";
import Button from "./Button";

const World = () => {
  const [expandedIndex, setExpandedIndex] = useState(1);
  
  const points = [
    {
      title: "Shaping MotionZ Collectively",
      description: "Participate in the governance of the MotionZ ecosystem and have a say in the future of the Design Layer.",
    },
    {
      title: "Unlocking Economic Opportunity",
      description: "MotionZ serves as the index for the design economy, providing holders with exposure to a diversified portfolio of creative assets and AI-driven design tools.",
    },
    {
      title: "Sharing Value Accrued",
      description: "A portion of the value generated by the MotionZ ecosystem is distributed back to the community, rewarding long-term participants and contributors.",
    },
  ];

  return (
    <section id="world" className="bg-white py-32">
      <div className="container mx-auto px-3 md:px-10">
        <div className="flex flex-col items-center">
          <p className="font-general text-sm uppercase md:text-[10px] text-black mb-5">
            the symbiotic world
          </p>
          
          <AnimatedTitle
            title="the symbi<b>o</b>tic world <br /> powered by m<b>o</b>tionz"
            containerClass="!text-black text-center"
          />

          <div className="mt-20 flex w-full flex-col items-center gap-10 lg:flex-row lg:items-start lg:justify-between">
            <div className="relative flex w-full max-w-md flex-col gap-5">
              {points.map((point, index) => (
                <div
                  key={index}
                  className={`cursor-pointer border-b border-black/10 pb-5 transition-all duration-300 ${
                    expandedIndex === index ? "opacity-100" : "opacity-50 hover:opacity-80"
                  }`}
                  onClick={() => setExpandedIndex(index)}
                >
                  <h3 className="font-zentry text-2xl uppercase md:text-3xl">
                    {point.title}
                  </h3>
                  {expandedIndex === index && (
                    <p className="mt-3 font-circular-web text-lg text-black/70">
                      {point.description}
                    </p>
                  )}
                </div>
              ))}
              
              <Button 
                title="Enter Blog" 
                containerClass="mt-10 bg-black text-white px-10"
              />
            </div>

            <div className="relative flex-center size-80 md:size-[30rem]">
              <div className="absolute-center size-full rounded-full border-2 border-black/5 animate-[spin_20s_linear_infinite]" />
              <div className="absolute-center size-[80%] rounded-full border border-black/10 animate-[spin_15s_linear_infinite_reverse]" />
              
              <img 
                src="img/token.png" 
                alt="MotionZ Token"
                className="z-10 size-40 object-contain md:size-64 drop-shadow-2xl"
              />
              
              {/* Floating elements */}
              <div className="absolute top-10 left-10 size-4 rounded-full bg-violet-500 animate-bounce" />
              <div className="absolute bottom-20 right-10 size-6 rounded-full bg-yellow-300 animate-pulse" />
              <div className="absolute top-1/2 -right-5 size-3 rounded-full bg-blue-500 animate-bounce delay-100" />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default World;
